version: '3'

services:
  slack-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: gen-alpha-slack-bot
    container_name: gen-alpha-slack-bot
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 